# Generated by Django 5.1.2 on 2024-11-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_image',
            field=models.URLField(verbose_name='image'),
        ),
    ]
