# Generated by Django 5.1.2 on 2024-12-21 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_cart_unit_order_unit_review_image_review_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.CreateModel(
            name='Review_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, default='', null=True, verbose_name='image')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.review')),
            ],
        ),
    ]
