# Generated by Django 5.1.2 on 2024-11-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_alter_wishlist_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, help_text='Rating should be between 1 and 5'),
        ),
    ]
