# Generated by Django 5.1.2 on 2024-11-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_image',
            field=models.URLField(verbose_name='image'),
        ),
    ]
