# Generated by Django 5.1.2 on 2024-11-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_alter_cart_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unit',
            field=models.CharField(default='Kg', max_length=10),
        ),
    ]
